# ============================================================================
#
# Makefile
#
# Module Makefile
#
# $Id: Makefile,v 1.2 2003/01/07 20:53:05 youngd Exp $
#
# Contents Copyright (c) 2000-2002, Digiship Corp.
#
# Darren Young
# darren_young@yahoo.com
#
# ============================================================================
#
# vim:set noexpandtab:
#
# ============================================================================


.PHONY : all clean docs install

all : clean install docs

clean :
	@echo "Making $@"

docs :


install :
	sudo rm -fr /tfd/modules/*
	sudo cp -dpR * /tfd/modules
