# ============================================================================
#
# XMLEDI.pod
#
# POD Documentation for the XMLEDI module
#
# $Id: XMLEDI.pod,v 1.1.1.1 2002/07/13 04:30:35 youngd Exp $
#
# Contents Copyright (c) 2000-2002 Digiship Corp.
#
# Darren Young
# darren_young@yahoo.com
#
# ============================================================================

=head1 NAME

XMLEDI

=head1 SYNOPSIS

<pre>use XMLEDI;</pre>

=head1 DESCRIPTION

=head1 INSTALLATION

=head1 METHODS

=head1 USAGE

=head1 EXAMPLE OUTPUT

=head1 VERSION

$Id: XMLEDI.pod,v 1.1.1.1 2002/07/13 04:30:35 youngd Exp $

=head1 COPYRIGHT

=head1 AUTHORS

=head1 SEE ALSO

