# ============================================================================
#
# RSMON Makefile
#
# $Id: Makefile,v 1.1.1.1 2002/07/13 04:30:35 youngd Exp $
#
# Contents Copyright (c) 2000, 2001 Digiship Corp.
#
# Darren Young
# youngd@digiship.com
#
# ============================================================================
#
# $Log: Makefile,v $
# Revision 1.1.1.1  2002/07/13 04:30:35  youngd
# initial import
#
# Revision 1.1.1.1  2001/12/15 18:17:56  youngd
# new import
#
# Revision 1.1.1.1  2001/12/12 19:00:28  youngd
# initial import
#
# Revision 1.3  2001/02/23 19:57:13  deploy
# Adjusted to take into account the new logfile parameter
#
# Revision 1.2  2001/02/23 19:31:32  deploy
# Added Log header
#
#
# ============================================================================


all : rsmon

rsmon :
	@echo 'Making $@'
	@chmod 755 rsmon.pl
