# ============================================================================
#
# Makefile Template
#
# Description for this makefile
#
# $Id: Makefile.tmpl,v 1.1 2002/08/20 02:47:52 youngd Exp $
#
# Contents Copyright (c) 2002, Transport Investments, Inc.
#
# Darren Young [darren@younghome.com]
#
# ============================================================================
#
# ChangeLog
#
# $Log: Makefile.tmpl,v $
# Revision 1.1  2002/08/20 02:47:52  youngd
# * Initial version
#
# ============================================================================
